---
- name: Instalar Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Habilitar y arrancar Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Configurar Nginx como reverse proxy para el cliente
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;

          server_name _;

          location / {
              proxy_pass http://localhost:3000;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
          }
      }
  notify:
    - Reload Nginx
