---
# =====================================
# PLAYBOOK: DESPLIEGUE EN LA NUBE
# Descripción: Configura una instancia en la nube (con GitHub Actions) para ejecutar la aplicación
# =====================================

- name: Despliegue en la nube 
  hosts: all
  become: true
  
  vars:
    # CONFIGURACIÓN BÁSICA DEL PROYECTO
    # ----------------------------------
    # Nombre del proyecto
    project_name: "app"
    
    # Usuario remoto (pasado desde el workflow)
    remote_user: "{{ remote_user | default('root') }}"
  
    # Directorio raíz del proyecto (se ajusta automáticamente según el usuario)
    project_root: "{{ '/home/' + remote_user if remote_user != 'root' else '/root' }}/{{ project_name }}"
    
    # Modo de despliegue (false = usar imágenes preconstruidas [RECOMENDADO], true = clonar y construir)
    clone_repos: false

    # Variables para localizar archivos (pasadas desde el workflow)
    workspace_root: "{{ workspace_root | default(playbook_dir + '/../../..') }}"
    deployment_dir: "{{ deployment_dir | default('deployments/apicore-gm-client') }}"
    
    # Directorio local donde están los archivos a copiar (docker-compose.yml y otros archivos necesarios)
    local_files_dir: "{{ workspace_root }}/{{ deployment_dir }}"
    
    # Archivos adicionales a copiar (opcional)
    additional_files:
      - "init.sql"
    
    # CONFIGURACIÓN DE SERVICIOS
    # --------------------------
    # Prefijo común para las imágenes Docker (para Docker Hub dejar vacío)
    docker_registry: ""
    
    # Definición de servicios
    services:
      - name: "core"                     # Nombre interno del servicio
        type: "api"                      # Tipo: api o frontend
        image: "thecariah/api-core-test" # Imagen Docker
        tag: "latest"                    # Tag de la imagen
        port: 3001                       # Puerto en el host
        env_var: "API_CORE_IMAGE"        # Nombre de variable para el .env
        api_prefix: "api-core"           # Prefijo para la ruta de API en Nginx
      
      - name: "gm"
        type: "api"
        image: "thecariah/api-gm-test"
        tag: "latest"
        port: 3002
        env_var: "API_GM_IMAGE"
        api_prefix: "api-gm"
      
      - name: "client"
        type: "frontend"
        image: "thecariah/client-test"
        tag: "latest"
        port: 3000
        env_var: "CLIENT_IMAGE"

    # Repositorios a clonar (solo necesario cuando clone_repos: true)
    service_repos:
      - name: "api-core"  # Nombre de la carpeta donde se clonará
        url: "https://github.com/infra-sandbox/api-core-test.git"
        branch: "main"
        env_var: "API_CORE_PATH"
        service: "core"  # Debe coincidir con un servicio en la sección 'services'
      
      - name: "api-gm"
        url: "https://github.com/infra-sandbox/api-gm-test.git"
        branch: "main"
        env_var: "API_GM_PATH"
        service: "gm"
      
      - name: "client"
        url: "https://github.com/infra-sandbox/client-test.git"
        branch: "main"
        env_var: "CLIENT_PATH"
        service: "client"

    # Variables globales de entorno (inyectadas desde GitHub Secrets) (modifica a tu conveniencia)
    global_env_vars:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      MONGO_USERNAME: "{{ mongo_username }}"
      MONGO_PASSWORD: "{{ mongo_password }}"
      INIT_SQL_PATH: "{{ project_root }}/init.sql"
    
    # CONFIGURACIÓN DE NGINX
    # ---------------------    
    # Nombre del servidor (dominio o "_" para local)
    server_name: "_"
    
    # Para SSL (opcional, solo si tienes dominio)
    enable_ssl: false
    # admin_email: "carolina.antillanca@usach.cl"
    # ssl_cert_path: "/etc/letsencrypt/live/{{ server_name }}/fullchain.pem"
    # ssl_key_path: "/etc/letsencrypt/live/{{ server_name }}/privkey.pem"
    
  roles:
    - python
    - docker
    - { role: ssl, when: "enable_ssl | bool" }
    - nginx
    - provision

# INSTRUCCIONES:
#
# 1. CÓMO AÑADIR UN NUEVO SERVICIO:
#    Copia uno de los bloques de servicio existentes y modifica sus valores.
#    Ejemplo:
#
#    - name: "nuevo-servicio"          # Nombre único del servicio
#      type: "api"                     # Tipo: api o frontend
#      image: "usuario/nueva-imagen"   # Imagen Docker (solo si clone_repos: false)
#      tag: "latest"                   # Tag de la imagen (solo si clone_repos: false)
#      port: 3003                      # Puerto en el host
#      env_var: "NUEVO_SERVICIO_IMAGE" # Nombre de variable en el .env
#      api_prefix: "nuevo-api"         # Ruta de API en Nginx (solo si es tipo api, si es frontend, no es necesario)
#
# 2. MODO DE DESPLIEGUE:
#    El playbook soporta dos modos de despliegue controlados por la variable 'clone_repos':
#
#    a) clone_repos: false (RECOMENDADO)
#       - Usa imágenes Docker preconstruidas
#       - Requiere que TODOS los servicios tengan 'image' y 'tag' definidos
#       - NO requiere configurar 'service_repos'
#       - Más rápido y más estable para producción
#
#    b) clone_repos: true
#       - Clona los repositorios y construye las imágenes en la instancia
#       - NO definir 'image' ni 'tag' en los servicios
#       - REQUIERE configurar 'service_repos' con todos los repositorios
#       - Ejemplo de configuración de 'service_repos':
#
#         service_repos:
#           - name: "api-core"             # Nombre de la carpeta donde se clonará
#             url: "https://github.com/tu-org/api-core.git"
#             branch: "main"               # Rama a clonar
#             env_var: "API_CORE_PATH"     # Variable para el .env
#             service: "core"              # Debe coincidir con el 'name' en la sección 'services'
#
# 3. VARIABLES DE ENTORNO (se inyectarán en el archivo .env):
#    - Específicas de un servicio: Añádelas dentro de env_vars en el servicio
#    - Globales para todos: Añádelas en global_env_vars
#    - Puedes usar secretos de GitHub Actions para estas variables.
#
# 4. CONFIGURACIÓN DE NGINX:
#    - Los servicios tipo "api" generan automáticamente una ruta en Nginx usando api_prefix
#    - Un único servicio tipo "frontend" será accesible en la ruta raíz (/)
#
# 5. SECRETOS EN GITHUB ACTIONS PARA BASES DE DATOS:
#    Ajusta los nombres según tu configuración, este es un ejemplo:
#    - POSTGRES_USER: Usuario para PostgreSQL
#    - POSTGRES_PASSWORD: Contraseña para PostgreSQL
#    - POSTGRES_DB: Nombre de la base de datos PostgreSQL
