---
- name: Despliegue de apicore-gm-client en instancia EC2 AWS con Nginx
  hosts: all
  become: true
  vars:
    project_root: "/home/ubuntu/infra-sandbox"
    compose_path: "/home/ubuntu/infra-sandbox/deployment-kit/sandbox/apicore-gm-client"
    clone_repos: false
  roles:
    - python
    - docker
    - nginx
    - provision
