---
# =====================================
# PLAYBOOK: DESPLIEGUE EN VM DIINF o LOCAL (CONFIGURACIÓN PARA clone_repos: false)
# Descripción: Configura una máquina para desplegar una aplicación
#              Despliega usando imágenes preconstruidas en Docker Hub.
# =====================================

- name: Despliegue en VMs del DIINF o local
  hosts: local
  become: true
  
  vars:
    # CONFIGURACIÓN BÁSICA DEL PROYECTO
    # ----------------------------------
    # Nombre del proyecto
    project_name: "apicore-gm-client"
    
    # Directorio raíz del proyecto (se ejecuta desde el directorio raíz)
    project_root: "{{ playbook_dir | dirname | dirname }}"
    
    # Modo de despliegue (false = usar imágenes preconstruidas [RECOMENDADO], true = clonar y construir)
    clone_repos: false

    # Ruta a docker-compose.yml y .env (deben ya existir)
    docker_compose_path: "{{ project_root }}/docker-compose.yml"
    env_file_path: "{{ project_root }}/.env"
    
    # CONFIGURACIÓN DE SERVICIOS
    # --------------------------
    # Prefijo común para las imágenes Docker (para Docker Hub dejar vacío)
    docker_registry: ""
    
    # Definición de servicios
    services:
      - name: "core"
        type: "api"
        image: "thecariah/api-core-test"
        tag: "latest"
        port: 3001
        api_prefix: "api-core"
      
      - name: "gm"
        type: "api"
        image: "thecariah/api-gm-test"
        tag: "latest"
        port: 3002
        api_prefix: "api-gm"
      
      - name: "client"
        type: "frontend"
        image: "thecariah/client-test"
        tag: "latest"
        port: 3000
        frontend_prefix: "/"
    
    # CONFIGURACIÓN DE NGINX
    # ---------------------    
    # Nombre del servidor (dominio de la VM o "_" para local)
    server_name: "felucia.diinf.usach.cl"
    
    # Para SSL (enable_ssl: true -> si hay dominio, enable_ssl: false -> sin dominio / local)
    enable_ssl: true
    admin_email: "carolina.antillanca@usach.cl"
    ssl_cert_path: "/etc/letsencrypt/live/{{ server_name }}/fullchain.pem"
    ssl_key_path: "/etc/letsencrypt/live/{{ server_name }}/privkey.pem"
    
  roles:
    - firewall
    - python
    - docker
    - { role: ssl, when: "enable_ssl | bool" }
    - nginx
    - provision
