---
- name: Configurar usuario administrador
  include_tasks: setup_admin_user.yml

- name: Configurar gamificación
  include_tasks: configure_gamification.yml

- name: Configurar cuestionarios por defecto
  include_tasks: setup_questionnaires.yml

- name: Mostrar mensaje final de configuración completada
  debug:
    msg:
      - "==========================================="
      - " CONFIGURACIÓN POST-DESPLIEGUE COMPLETADA"
      - "==========================================="
      - ""
      - "Usuario administrador:"
      - "   Email: {{ admin_email }}"
      - "   Contraseña: {{ admin_password }}"
      - ""
      - "Servicios disponibles:"
      - "   NEURONE Trivia: http://localhost:4200 -> Juego principal"
      - "   NEURONE Core: http://localhost:3000 -> Análisis y documentos"
      - "   NEURONE GM: http://localhost:4201 -> Panel de Gamificación"
      - ""
      - "Gamificación: ACTIVADA AUTOMÁTICAMENTE"
      - "Cuestionarios: CONFIGURADOS AUTOMÁTICAMENTE"
      - "   - Pre-test, Post-test, Post-study listos"
      - "   - Modificables en: ansible/roles/post-deployment/vars/questionnaires.yml"
      - ""
      - " Ahora puedes iniciar sesión con las credenciales de admin en Trivia y GM."
      - " Para NEURONE Core, debes registrar un usuario en http://localhost:3000/register "
      - "==========================================="
