---
# =====================================
# PLAYBOOK: DESPLIEGUE EN VM DIINF o LOCAL (Ubuntu)
# Descripción: Configura una máquina para desplegar una aplicación
# =====================================
- name: Despliegue en VMs del DIINF o local
  hosts: local
  become: true
  
  vars:
    # CONFIGURACIÓN BÁSICA DEL PROYECTO
    # ----------------------------------
    # Nombre del proyecto
    project_name: "interaction-site"
    
    # Directorio raíz del proyecto (se ejecuta desde el directorio raíz)
    project_root: "{{ playbook_dir | dirname | dirname }}"
    
    # Modo de despliegue (false = usar imágenes preconstruidas [RECOMENDADO], true = clonar y construir)
    clone_repos: true

    # Se activa forzar construcción imagenes (ya que se eliminó tarea de actualizar repositorios debido a que son privados)
    force_build: true

    # Ruta a docker-compose.yml y .env
    docker_compose_path: "{{ project_root }}/docker-compose.yml"
    env_file_path: "{{ project_root }}/.env"

    # Determina si el proyecto utiliza un archivo .env para el docker compose
    use_env_file: false
    
    # CONFIGURACIÓN DE SERVICIOS DOCKER
    # ---------------------------------
    
    # Definición de servicios
    services:
      - name: "backend"
        type: "api"
        port: 3000
        api_prefix: "api"
      
      - name: "spa"
        type: "frontend"
        port: 8080
        frontend_prefix: "/"

      - name: "dashboard"
        type: "frontend"
        port: 9090
        frontend_prefix: "/"

    service_repos:
      - name: "interaction-backend"
        url: "https://github.com/InTeractiOn-Sites/interaction-backend.git"
        branch: "deploy_diinf"
        service: "backend"
      
      - name: "interaction-spa"
        url: "https://github.com/InTeractiOn-Sites/interaction-spa.git"
        branch: "deploy_diinf"
        service: "spa"
      
      - name: "interaction-dashboard"
        url: "https://github.com/InTeractiOn-Sites/interaction-dashboard.git"
        branch: "deploy_diinf"
        service: "dashboard"
    
    # CONFIGURACIÓN DE NGINX MULTI-DOMINIO
    # ---------------------    
    # Activar configuración multi-dominio
    nginx_multi_site: true

    # Definición de dominios y servicios por dominio
    nginx_sites:
      - server_name: "felucia.diinf.usach.cl"
        services:
          - name: "backend"
          - name: "spa"

      - server_name: "interaction-dashboard.diinf.usach.cl"
        services:
          - name: "backend"
          - name: "dashboard"

    # Controla si las rutas definidas en Nginx deben terminar con una barra "/".
    # true  ➝ Nginx agregará "/" al final del proxy_pass (ej: proxy_pass http://localhost:3000/).
    # false ➝ Nginx no agregará "/" al final (ej: proxy_pass http://localhost:3000).
    use_trailing_slash: false
    
    # Para SSL (enable_ssl: true -> si hay dominio, enable_ssl: false -> sin dominio / local)
    enable_ssl: true
    admin_email: "carolina.antillanca@usach.cl"
    
  roles:
    - firewall
    - python
    - docker
    - { role: ssl, when: "enable_ssl | bool" }
    - nginx
    - provision
