services:
  backend:
    container_name: interaction-backend
    build:
      context: ./interaction-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - interaction-network

  dashboard:
    container_name: interaction-dashboard
    build:
      context: ./interaction-dashboard
    ports:
      - "9090:9090"
    networks:
      - interaction-network

  spa:
    container_name: interaction-spa
    build:
      context: ./interaction-spa
    ports:
      - "8080:8080"
    networks:
      - interaction-network

  mongo:
    image: mongo:6
    container_name: interaction-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - interaction-network
  
networks:
  interaction-network:
    driver: bridge

volumes:
  mongo_data:
