services:
  backend:
    container_name: interaction-backend
    image: thecariah/interaction-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - interaction-network

  dashboard:
    container_name: interaction-dashboard
    image: thecariah/interaction-dashboard:latest
    ports:
      - "9090:9090"
    env_file:
      - .env
    networks:
      - interaction-network

  spa:
    container_name: interaction-spa
    image: thecariah/interaction-spa:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - interaction-network

  mongo:
    image: mongo:6
    container_name: interaction-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - interaction-network

networks:
  interaction-network:
    driver: bridge

volumes:
  mongo_data:
