# ========================================================
# WORKFLOW: DESPLIEGUE DE INSTANCIA AWS CON TERRAFORM
# Descripci贸n: Crea y configura una instancia EC2 en AWS utilizando Terraform de forma automatizada.
# ========================================================
name: AWS Terraform Instance Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/aws-terraform-instance.yml'

jobs:
  deploy-instance:
    name: Deploy AWS Instance with Terraform
    runs-on: ubuntu-latest

    # Variables de entorno necesarias para la autenticaci贸n con AWS y Terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_inline_public_key: ${{ secrets.INLINE_PUBLIC_KEY }}

    defaults:
      run:
        working-directory: terraform

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Paso 3: Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # Paso 4: Validar la configuraci贸n de Terraform
      - name: Terraform Validate
        run: terraform validate

      # Paso 5: Generar un plan de ejecuci贸n de Terraform
      - name: Terraform Plan
        run: terraform plan

      # Paso 6: Aplicar los cambios con Terraform.
      - name: Terraform Apply
        run: terraform apply -auto-approve
