# ========================================================
# WORKFLOW: BUILD Y PUSH DE IMAGEN DOCKER
# Descripción: Construye y publica una imagen en Docker Hub cuando se realizan cambios en el repositorio.
# ========================================================
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el código fuente del repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    # Paso 2: Configurar Docker Buildx para construir imágenes
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Paso 3: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Paso 4: Construir y publicar la imagen Docker
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags:
          thecariah/app:latest

        # NOTAS SOBRE LAS ETIQUETAS:
        # - "latest": Siempre apunta a la última versión publicada.
        # - "${{ github.sha }}": Permite identificar la imagen exacta basada en el commit.
        # - "v1.0.0": Puedes usar un esquema de versionamiento semántico (major.minor.patch).
