---
# Instalación de Docker y Docker Compose

- name: Verificar si Docker está instalado
  stat:
    path: /usr/bin/docker
  register: docker_check

- name: Instalar dependencias del sistema para Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: true
  when: not docker_check.stat.exists

- name: Agregar clave GPG oficial de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  when: not docker_check.stat.exists

- name: Agregar repositorio de Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true
  when: not docker_check.stat.exists

- name: Instalar Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  become: true
  when: not docker_check.stat.exists

- name: Verificar si Docker Compose está instalado
  stat:
    path: /usr/libexec/docker/cli-plugins/docker-compose
  register: compose_check

- name: Instalar Docker Compose plugin (v2)
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: true
  become: true
  when: not compose_check.stat.exists

- name: Agregar usuario actual al grupo docker
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
  when: not docker_check.stat.exists

- name: Reinicia sesión si es primera vez
  debug:
    msg: "El usuario fue agregado al grupo docker. Reinicia sesión si es necesario."
  when: not docker_check.stat.exists
