---
# =====================================
# ROL: PYTHON
# Descripción: Instala Python y dependencias necesarias para Docker y gestión de contenedores
# =====================================

- name: Verificar si hay procesos APT en ejecución (diagnóstico)
  shell: |
    pgrep -ax apt || echo "No hay procesos APT"
  register: apt_process_check
  ignore_errors: true
  changed_when: false
  become: true

- name: Mostrar procesos APT encontrados (si hay)
  debug:
    var: apt_process_check.stdout_lines

# Esperar hasta que no haya procesos APT bloqueando (bloqueo común en instancias nuevas de Digital Ocean)
- name: Esperar hasta que APT esté libre
  shell: |
    while pgrep -x apt || fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
          fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || \
          fuser /var/cache/apt/archives/lock >/dev/null 2>&1; do
      echo "Esperando que se liberen los locks de APT..."
      sleep 5
    done
  retries: 36  # 36 * 5s = 3 minutos máx
  delay: 5
  register: apt_wait
  until: apt_wait.rc == 0
  become: true

# Instalar Python 3
- name: Asegurar que Python 3 esté instalado
  apt:
    name: python3
    state: present
    update_cache: yes
  become: true

# Instalar pip3 para gestión de paquetes Python
- name: Asegurar que pip3 esté instalado
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: true

# Instalar dependencias específicas de Python
# NOTA: Puedes modificar esta lista según las necesidades del proyecto (ya tiene versiones compatibles)
- name: Instalar dependencias Python necesarias
  pip:
    name:
      - docker==6.1.3         # SDK de Docker para Python
      - docker-compose==1.29.2 # Versión compatible con el plugin docker-compose
      - requests==2.28.2      # Librería para realizar peticiones HTTP
      - urllib3==1.26.20      # Dependencia de requests
      - requests_unixsocket   # Para comunicarse con sockets Unix
    executable: pip3
  become: true