---
# =====================================
# ROL: PROVISION - IMÁGENES PRECONSTRUIDAS
# Descripción: Descarga imágenes Docker preconstruidas y configura el despliegue
# =====================================

# Descargar imágenes Docker desde el registro (Docker Hub u otro)
- name: Descargar imágenes Docker preconstruidas
  command: docker pull {{ item }}
  loop:
    - "{{ docker_registry | default('') }}{{ service1_image }}:{{ service1_tag | default('latest') }}"
    - "{{ docker_registry | default('') }}{{ service2_image }}:{{ service2_tag | default('latest') }}"
    - "{{ docker_registry | default('') }}{{ service3_image }}:{{ service3_tag | default('latest') }}"
  # NOTA: Personaliza la lista con las imágenes que necesites

# Crear archivo .env con las variables necesarias para docker-compose
- name: Crear archivo .env con rutas necesarias
  copy:
    dest: "{{ compose_path }}/.env"
    content: |
      # Variables para las imágenes de servicios
      SERVICE1_IMAGE={{ docker_registry | default('') }}{{ service1_image }}:{{ service1_tag | default('latest') }}
      SERVICE2_IMAGE={{ docker_registry | default('') }}{{ service2_image }}:{{ service2_tag | default('latest') }}
      SERVICE3_IMAGE={{ docker_registry | default('') }}{{ service3_image }}:{{ service3_tag | default('latest') }}

      # Variables adicionales (bases de datos, configuración, etc.)
      {{ additional_env_vars | default('') }}
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'

# Levantar los contenedores
- name: Levantar contenedores con Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ compose_path }}"
