version: "3.8"

services:
  core:
    build:
      context: ${API_CORE_PATH}
    image: core-api
    container_name: core-api
    ports:
      - "3001:3001"
    networks:
      - app-network

  gm:
    build:
      context: ${API_GM_PATH}
    image: gm-api
    container_name: gm-api
    ports:
      - "3002:3002"
    networks:
      - app-network

  client:
    build:
      context: ${CLIENT_PATH}
    image: client-app
    container_name: client-app
    ports:
      - "3000:3000"
    depends_on:
      - core
      - gm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
