version: "3.8"

services:
  core:
    build:
      context: ${API_CORE_PATH}
    image: core-api
    container_name: core-api
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/coredb
    networks:
      - app-network

  gm:
    build:
      context: ${API_GM_PATH}
    image: gm-api
    container_name: gm-api
    ports:
      - "3002:3002"
    environment:
      - POSTGRES_URI=postgresql://gm_user:gm_pass@postgres:5432/gmdb
    networks:
      - app-network

  client:
    build:
      context: ${CLIENT_PATH}
    image: client-app
    container_name: client-app
    ports:
      - "3000:3000"
    depends_on:
      - core
      - gm
    networks:
      - app-network
  
  mongo:
    image: mongo:5
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
  
  postgres:
    image: postgres:15
    container_name: gm-postgres
    environment:
      POSTGRES_DB: gmdb
      POSTGRES_USER: gm_user
      POSTGRES_PASSWORD: gm_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${INIT_SQL_PATH}:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  postgres_data: