---
# Usar imágenes preconstruidas o clonar repositorios
- name: Usar imágenes preconstruidas o clonar repositorios
  include_tasks: use_prebuilt_images.yml
  when: not clone_repos | default(false)

- name: Clonar repositorios y construir imágenes localmente
  include_tasks: clone_repos.yml
  when: clone_repos | default(false)

# Levantar contenedores con Docker Compose
- name: Levantar contenedores con Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ compose_path }}"

- name: Verificar el estado de los contenedores
  command: docker ps
  register: docker_ps_output
  changed_when: false
