- name: Descargar imágenes Docker preconstruidas
  command: docker pull {{ item }}
  loop:
    - thecariah/api-core-test:latest
    - thecariah/api-gm-test:latest
    - thecariah/client-test:latest

- name: Clonar repositorio deployment-kit para obtener docker-compose.yml
  git:
    repo: https://github.com/infra-sandbox/deployment-kit.git
    dest: "{{ project_root }}/deployment-kit"
    version: main

- name: Crear carpeta de Docker Compose si no existe
  file:
    path: "{{ compose_path }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copiar archivo init.sql al directorio del Compose
  copy:
    src: "{{ playbook_dir }}/../../../init.sql"
    dest: "{{ compose_path }}/init.sql"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Crear archivo .env con rutas necesarias
  copy:
    dest: "{{ compose_path }}/.env"
    content: |
      API_CORE_IMAGE=thecariah/api-core-test:latest
      API_GM_IMAGE=thecariah/api-gm-test:latest
      CLIENT_IMAGE=thecariah/client-test:latest
      INIT_SQL_PATH={{ compose_path }}/init.sql
    owner: ubuntu
    group: ubuntu
    mode: '0644'
