name: Sandbox Terraform Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'sandbox/apicore-gm-client/terraform/**'
      - '.github/workflows/sandbox.yml'

jobs:
  deploy-sandbox:
    name: Deploy apicore-gm-client to AWS EC2
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_inline_public_key: ${{ secrets.INLINE_PUBLIC_KEY }}

    defaults:
      run:
        working-directory: sandbox/apicore-gm-client/terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Debug public key and TF vars
        run: |
          echo "First 100 chars of INLINE_PUBLIC_KEY:"
          echo "${{ secrets.INLINE_PUBLIC_KEY }}" | head -c 100
          echo ""
          echo "TF_VAR_ environment variables:"
          env | grep TF_VAR_

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
