name: DIINF Deployment via Local Proxy

on:
  workflow_dispatch:

jobs:
  provision-diinf:
    name: Provision DIINF via SSH Proxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Write SSH Private Key
        run: |
          echo "${{ secrets.DIINF_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Try SSH Connection (via Proxy)
        run: |
          ansible -m ping all -i "localhost," \
            --user cantillanca \
            --private-key private_key.pem \
            -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand=\"ssh -W %h:%p -p 2222 cantillanca@192.168.1.17\"'"

      - name: Run Ansible Playbook to Configure DIINF
        run: |
          cd sandbox/apicore-gm-client && \
          ansible-playbook deploy/playbooks/deploy_diinf.yml \
            -i "localhost," \
            --user cantillanca \
            --private-key private_key.pem \
            -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand=\"ssh -W %h:%p -p 2222 cantillanca@192.168.1.17\"'"

      - name: Cleanup SSH Key
        run: rm -f private_key.pem
