name: Deploy to DIINF VM using SSH over HTTPS (443)

on:
  workflow_dispatch:  # Permite iniciar el workflow manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key with Passphrase
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host github.com\n\tHostname ssh.github.com\n\tPort 443\n\tUser git\n\tIdentityFile ~/.ssh/id_ed25519\n\tPreferredAuthentications publickey\n" > ~/.ssh/config
          ssh -T -p 443 git@ssh.github.com

      - name: Connect to DIINF VM using SSH with Passphrase
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}       # IP la máquina del DIINF
          username: ${{ secrets.USERNAME }} # Usuario en la VM
          key: ${{ secrets.SSH_KEY }}     # Clave SSH confgurada
          passphrase: ${{ secrets.PASSPHRASE }} # Passphrase SSH
          port: 443                       # Se utiliza el puerto 443 porque el 22 está bloqueado
          script: |
            whoami
            hostname
            uptime
