name: Deploy to DIINF VM via VPN

on:
  workflow_dispatch:  # Permite iniciar el workflow manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Create VPN Config Securely
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > client.ovpn
          chmod 600 client.ovpn

      - name: Connect to VPN (Debug Mode)
        run: |
          sudo openvpn --config client.ovpn --auth-user-pass <(echo -e "${{ secrets.OVPN_USERNAME }}\n${{ secrets.OVPN_PASSWORD }}") \
          --auth-nocache --verb 4 --log openvpn_debug.log
          sudo chmod 666 openvpn_debug.log
          cat openvpn_debug.log

      - name: Use SSH to Deploy with Password
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            whoami
            hostname
            uptime
