name: Deploy to DIINF VM via VPN

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Create VPN Config Securely
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > client.ovpn
          chmod 600 client.ovpn

      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v2
        with:
          config_file: client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.USER_KEY }}

      - name: Use SSH to Deploy with Password
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.PASSWORD }}  # Tu contraseña SSH de la VM
          port: 22
          script: |
            whoami
            hostname
            uptime
