---
# =====================================
# ROL: PROVISION
# Descripción: Orquesta el despliegue de servicios usando Docker
# =====================================

# Usar imágenes preconstruidas de Docker Hub
- name: Usar imágenes preconstruidas
  include_tasks: use_prebuilt_images.yml
  when: not clone_repos | default(false)
  tags:
    - provision
    - docker

# Clonar repositorios y construir imágenes localmente
- name: Clonar repositorios y construir imágenes localmente
  include_tasks: clone_repos.yml
  when: clone_repos | default(false)
  tags:
    - provision
    - docker
    - clone

# Una vez configurada la aplicación, verificar el estado
- name: Verificar el estado de los contenedores
  command: docker ps
  register: docker_ps_output
  changed_when: false
  tags:
    - provision
    - status

# Mostrar resumen del despliegue
- name: Mostrar resumen del despliegue
  debug:
    msg: |
      ==========================================================
      Despliegue completado con éxito
      ==========================================================
      
      Resumen:
        - Aplicación: {{ project_name }}
        - Modo: {% if clone_repos %}Repositorios clonados{% else %}Imágenes preconstruidas{% endif %}
        - URL: http://{{ server_name if server_name != "_" else "localhost" }}
        
      Endpoints:
        - Frontend: http://{{ server_name if server_name != "_" else "localhost" }}
      {% for service in services %}
      {% if service.type == 'api' and service.api_prefix is defined %}
        - {{ service.name | capitalize }}: http://{{ server_name if server_name != "_" else "localhost" }}/{{ service.api_prefix }}
      {% endif %}
      {% endfor %}
      
      Para verificar logs:
        - docker logs [nombre_contenedor]
      ==========================================================
